spring:
  application:
    name: order-processing-system

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000

logging:
  file:
    name: logs/ops-logs.log
